apiVersion: v1
kind: ServiceAccount
metadata:
  name: findash-api-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "b1221721-b7b5-4d01-84ee-50446a1c0264"
  labels:
    azure.workload.identity/use: "true"